POST http://localhost:9876/api/users
Content-Type: application/json

{
  "login": "Alfred",
  "mail": "test@alior.pl"
}

###
POST http://localhost:9876/api/users
Content-Type: application/json

{
  "login": "juuulek"
}

###
POST http://localhost:9876/api/users
Content-Type: application/json

{
  "login": "yourmother13",
  "mail": "someimmatureemailaddress@gmail.com"
}

###
POST http://localhost:9876/api/users
Content-Type: application/json

{
  "login": "fourth"
}

###
POST http://localhost:9876/api/lists
Content-Type: application/json

{
  "name": "shopping",
  "ownerId": 2,
  "shared": [
    1,
    4
  ]
}

###
POST http://localhost:9876/api/lists
Content-Type: application/json

{
  "name": "secret shopping",
  "ownerId": 2
}

###
POST http://localhost:9876/api/tasks
Content-Type: application/json

{
  "name": "bułki",
  "listId": 1,
  "tags": "pieczywo"
}

###
POST http://localhost:9876/api/tasks
Content-Type: application/json

{
  "name": "gumy do żucia",
  "listId": 1
}

###
POST http://localhost:9876/api/tasks
Content-Type: application/json

{
  "name": "czekolada",
  "listId": 2,
  "description": "odkupić, bo jej zeżarłeś",
  "tags": "mleczne",
  "deadline": "11-05-2023 12:00"
}

###
POST http://localhost:9876/api/tasks
Content-Type: application/json

{
  "name": "monte",
  "listId": 1,
  "tags": "mleczne,dla niej",
  "deadline": "14-05-2023 12:00"
}

###
POST http://localhost:9876/api/tasks
Content-Type: application/json

{
  "name": "pluszak",
  "listId": 2,
  "description": "po porodzie",
  "appearance": "16-05-2023 00:00"
}

###
POST http://localhost:9876/api/filters
Content-Type: application/json

{
  "ownerId": 2,
  "lists": [
    1,
    2
  ],
  "includedTags": "pieczywo,mleczne"
}
